sonar.host.url=https://sonarcloud.io
sonar.organization=PetterAven
sonar.projectKey=omninexus_pos
sonar.projectName=OmniNexus POS
sonar.projectVersion=1.0

# Código fuente a analizar (Análisis Estático)
sonar.sources=lib
sonar.exclusions=lib/**/*.g.dart, lib/generated/**

# Pruebas Dinámicas y Cobertura
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8