name: Build macOS Release

on:
  workflow_dispatch: # Permite activar la compilación manualmente desde GitHub

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # O la versión que utilices
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Crea el archivo .env para evitar que el empaquetado de assets falle
      - name: Create dummy .env file
        run: touch .env

      - name: Build macOS App
        run: flutter build macos --release

      - name: Upload App Build
        uses: actions/upload-artifact@v4
        with:
          name: OmniNexus_POS_Mac
          path: build/macos/Build/Products/Release/